name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  issues: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: pypi

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          pip install build
          npm install -g semantic-release @semantic-release/exec @semantic-release/github @semantic-release/git

      - name: Run tests
        run: |
          pip install -e ".[dev]"
          python -m pytest

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get current HEAD sha before semantic-release
          BEFORE_SHA=$(git rev-parse HEAD)
          
          # Run semantic-release
          npx semantic-release
          
          # Get current HEAD sha after semantic-release
          AFTER_SHA=$(git rev-parse HEAD)
          
          # Check if semantic-release created a new commit (which means a release was made)
          if [ "$BEFORE_SHA" != "$AFTER_SHA" ]; then
            echo "released=true" >> $GITHUB_OUTPUT
            echo "Release was published!"
          else
            echo "released=false" >> $GITHUB_OUTPUT
            echo "No release was published."
          fi

      - name: Publish to PyPI
        if: steps.release.outputs.released == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
